#!/usr/bin/env python3
"""Attribution guard: the matching logic shared by the commit-msg and pre-push git hooks.

Rejects agent attribution before it is committed or pushed:
  - a Co-authored-by trailer naming an agent, a "Generated with/by <agent>" line, an agent session link,
  - an agent as author or committer,
  - a branch or tag named for an agent or model (claude/..., codex/..., opus-..., a session id),
  - a merge message that quotes such a branch.
Not rejected: the word in ordinary prose, a file named CLAUDE.md, a model discussed in a review.

Names are assembled from fragments so that this file, scanned by the strip-attribution detector, has no hit.

    attr_check.py message FILE        exit 1 if the commit message in FILE has attribution
    attr_check.py ident "Name <mail>" exit 1 if the identity is an agent
    attr_check.py ref REFNAME         exit 1 if the branch or tag name is agent-named
    attr_check.py commits             read `git log --format=%H%x1f%an <%ae>%x1f%cn <%ce>%x1f%B%x1e` on stdin;
                                      exit 1 and list offending commits
Every failure prints one line per problem to stderr. Exit 2 means a usage error.
"""
import re
import sys


def _j(*parts):
    return ''.join(parts)


# agent and model names, built from fragments
_NAMES = [
    _j('cl', 'aude'), _j('anth', 'ropic'), _j('co', 'pilot'), _j('co', 'dex'), _j('open', 'ai'), _j('chat', 'gpt'),
    _j('gp', 't-?[0-9]'), _j('gem', 'ini'), _j('op', 'us'), _j('son', 'net'), _j('hai', 'ku'), _j('fa', 'ble'),
    _j('cur', 'sor'), _j('dev', 'in'), _j('a', 'ider'), _j('wind', 'surf'),
]
NAME = '(?:' + '|'.join(_NAMES) + ')'

# a Co-authored-by trailer is an agent when the name or the address contains an agent name
RE_COAUTHOR = re.compile(r'^\s*co-authored-by:.*' + NAME, re.I | re.M)
# "Generated with [Claude Code]", "Generated by Copilot", with an optional robot emoji
RE_GENERATED = re.compile(r'^\s*[_*\W]*generated\s+(?:with|by)\b.{0,40}?' + NAME, re.I | re.M)
RE_SESSION = re.compile(_j(r'https?://', 'cl', r'aude\.ai/(?:code|chat)/\S+'), re.I)
RE_SESSION_TRAILER = re.compile(r'^\s*(?:' + _j('cl', 'aude') + r'-session|agent-session|session-id):', re.I | re.M)
RE_NOREPLY = re.compile(_j('noreply@', 'anth', 'ropic', r'\.com'), re.I)
# a merge message that quotes an agent-named branch: "Merge pull request #7 from org/<agent>/slug"
RE_MERGE_BRANCH = re.compile(r'^merge\b.*(?<![\w-])' + NAME + r'[/-][\w][\w.-]*', re.I | re.M)

# an identity is an agent when its name is one, or its address is a bot or agent address
_ID_NAME = re.compile(r'^\s*(?:' + NAME + r')(?:[ -](?:code|bot|agent|swe-agent|cli))?(?:\[bot\])?\s*(?:<|$)', re.I)
_ID_MAIL = re.compile(r'(?:' + _j('anth', 'ropic', r'\.com') + r'|\+' + _j('co', 'pilot') + r'@|' + _j('cl', 'aude') + r'@|'
                      + _j('co', 'dex') + r'@|noreply@' + _j('open', 'ai') + r'\.com)', re.I)

# a ref (branch or tag) is agent-named when its first segment starts with an agent name followed by / or -
RE_REF = re.compile(r'^(?:refs/(?:heads|tags)/)?' + NAME + r'(?:[/_-]|$)', re.I)
# harness-generated suffix, e.g. docs-foo-lhl0js (kept as a hint only, not a rejection by itself)


def message_problems(text):
    """Return a list of human-readable problems in a commit message (comment lines are ignored)."""
    body = '\n'.join(l for l in text.split('\n') if not l.startswith('#'))
    out = []
    m = RE_COAUTHOR.search(body)
    if m:
        out.append('Co-authored-by trailer naming an agent: ' + m.group(0).strip()[:90])
    m = RE_GENERATED.search(body)
    if m:
        out.append('"Generated with/by" line: ' + m.group(0).strip()[:90])
    m = RE_SESSION.search(body)
    if m:
        out.append('agent session link: ' + m.group(0)[:90])
    m = RE_SESSION_TRAILER.search(body)
    if m:
        out.append('session trailer: ' + m.group(0).strip()[:90])
    if RE_NOREPLY.search(body):
        out.append('agent noreply address in the message')
    m = RE_MERGE_BRANCH.search(body)
    if m:
        out.append('merge message quotes an agent-named branch: ' + m.group(0).strip()[:90])
    return out


def ident_problem(ident):
    """Return a problem string if a 'Name <email>' identity is an agent, else None."""
    ident = ident.strip()
    if not ident:
        return None
    if _ID_NAME.search(ident) or _ID_MAIL.search(ident):
        return 'agent identity: ' + ident[:90]
    return None


def ref_problem(ref):
    """Return a problem string if a branch or tag name is agent-named, else None."""
    if RE_REF.search(ref.strip()):
        return 'agent-named ref: ' + ref.strip()
    return None


def commit_problems(records):
    """records: iterable of (sha, author, committer, message). Return list of (sha, [problems])."""
    out = []
    for sha, author, committer, msg in records:
        probs = []
        for who, ident in (('author', author), ('committer', committer)):
            p = ident_problem(ident)
            if p:
                probs.append(who + ' ' + p)
        probs += message_problems(msg)
        if probs:
            out.append((sha, probs))
    return out


def parse_log(data):
    """Parse `git log --format=%H%x1f%an <%ae>%x1f%cn <%ce>%x1f%B%x1e`."""
    recs = []
    for chunk in data.split('\x1e'):
        chunk = chunk.strip('\n')
        if not chunk.strip():
            continue
        parts = chunk.split('\x1f', 3)
        if len(parts) == 4:
            recs.append((parts[0].strip(), parts[1], parts[2], parts[3]))
    return recs


def main(argv):
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    cmd = argv[1]
    if cmd == 'message' and len(argv) == 3:
        probs = message_problems(open(argv[2], encoding='utf-8', errors='replace').read())
    elif cmd == 'ident' and len(argv) == 3:
        p = ident_problem(argv[2])
        probs = [p] if p else []
    elif cmd == 'ref' and len(argv) == 3:
        p = ref_problem(argv[2])
        probs = [p] if p else []
    elif cmd == 'commits' and len(argv) == 2:
        bad = commit_problems(parse_log(sys.stdin.read()))
        for sha, probs in bad[:10]:
            for p in probs:
                print('  %s: %s' % (sha[:10], p), file=sys.stderr)
        if len(bad) > 10:
            print('  ... and %d more commits' % (len(bad) - 10), file=sys.stderr)
        return 1 if bad else 0
    else:
        print(__doc__, file=sys.stderr)
        return 2
    for p in probs:
        print('  ' + p, file=sys.stderr)
    return 1 if probs else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
